<?php

/**
 * Implements hook_block_info()
 */
function sape_block_block_info() {
  $blocks['sape_block_links'] = array (
    'info' => t('Sape links block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['sape_block_articles'] = array (
    'info' => t('Sape articles block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure()
 */
function sape_block_block_configure($delta = '') {
  $form = array();
  if ($delta == 'sape_block_links' || $delta == 'sape_block_articles') {
    $form['sape_block_user'] = array(
      '#type' => 'textfield',
      '#required' => TRUE,
      '#title' => t('User name'),
      '#description' => t('Sape user name'),
      '#default_value' => variable_get('sape_block_user'),
    );
    if($delta == 'sape_block_links') {
      $form['sape_block_options'] = array(
        '#type' => 'container',
        '#tree' => TRUE,
      );
      $form['sape_block_options']['verbose'] = array(
        '#type' => 'checkbox',
        '#title' => t('Verbose'),
        '#description' => t('Show errors'),
      );
      $form['sape_block_options']['debug'] = array(
        '#type' => 'checkbox',
        '#title' => t('Debug'),
        '#description' => t('Enable debug mode'),
      );
      $form['sape_block_options']['show_code'] = array(
        '#type' => 'checkbox',
        '#title' => t('Force show code'),
        '#description' => t('Always show check code'),
      );
      $default_values = variable_get('sape_block_links_options');
      if(is_array($default_values) && !empty($default_values)) {
        foreach($form['sape_block_options'] as $option => $value) {
          if(is_array($value)) {
            $form['sape_block_options'][$option]['#default_value'] = $default_values[$option];
          }
        }
      }
    }
  }
  return $form;
}

/**
 * Implements hook_block_save()
 */
function sape_block_block_save($delta = '', $edit = array()) {
  if($delta == 'sape_block_links' || $delta == 'sape_block_articles') {
    variable_set('sape_block_user', $edit['sape_block_user']);
  }
  if($delta == 'sape_block_links') {
    variable_set('sape_block_links_options', $edit['sape_block_options']);
  }
}

/**
 * Implements hook_block_view()
 */
function sape_block_block_view($delta = '') {
  $block = array();
  if ($delta == 'sape_block_links' || $delta == 'sape_block_articles') {
    $block['subject'] = NULL;
    $user = variable_get('sape_block_user');
    if(!empty($user)) {
      if (!defined('_SAPE_USER')) {
        define('_SAPE_USER', $user);
      }
      $sape_dir = DRUPAL_ROOT . '/' . _SAPE_USER;
      $sape_php = "$sape_dir/sape.php";
      if(file_prepare_directory($sape_dir)) {
        if(file_exists($sape_php)) {
          require_once($sape_php);
          $options = array();
          $options['charset'] = 'utf-8';
          if ($delta == 'sape_block_links') {
            $options += variable_get('sape_block_links_options');
            $sape_links = new SAPE_client($options);
            $block['content'] = $sape_links->return_links();
          }
          if ($delta == 'sape_block_articles') {
            $sape_article = new SAPE_articles($options);
            $block['content'] = $sape_article->return_announcements();
          }
        }
        else {
          drupal_set_message(t("File '$sape_php' not exist"), 'error');
        }
      }
      else {
        drupal_set_message(t("File '$sape_dir' not exist or not writable"), 'error');
      }
    }
  }
  return $block;
}
