<?php

/**
 * Support services.
 */
define('EXCHANGE_LINKS_SAPE', 'sape');
define('EXCHANGE_LINKS_MAINLINK', 'mainlink');
define('EXCHANGE_LINKS_LINKFEED', 'linkfeed');
define('EXCHANGE_LINKS_SETLINK', 'setlinks');

/**
 * Implements hook_menu()
 */
function exchange_links_menu() {
  $items['admin/structure/block/exchange_links_add'] = array(
    'title' => 'Add block exchange links',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('exchange_links_add_block_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'exchange_links.admin.inc',
  );
  $items['admin/structure/block/manage/exchange_links/%/delete'] = array(
    'title' => 'delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('exchange_links_del_block_form', 5),
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'exchange_links.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_block_configure().
 */
function exchange_links_block_configure($delta = 0) {

  $form['exchange_links_service'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#title' => t('Select service'),
    '#options' => exchange_links_services(),
    //'#description' => t(''),
  );
  $form['exchange_links_user'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('User'),
    //'#description' => t(''),
  );
  $form['exchange_links_debug'] = array(
    '#type' => 'checkbox',
    '#title' => t('Debug'),
    '#default_value' => FALSE,
    //'#description' => t(''),
  );
  $form['exchange_links_show_code'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show code'),
    '#default_value' => FALSE,
    //'#description' => t(''),
  );
  if($delta != 0) {
    $block = exchange_links_block_get($delta);
    $form['exchange_links_service']['#default_value'] = $block->service;
    $form['exchange_links_user']['#default_value'] = $block->user;
    $form['exchange_links_debug']['#default_value'] = $block->debug;
    $form['exchange_links_show_code'] ['#default_value'] = $block->show_code;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function exchange_links_block_save($delta = 0, $edit = array()) {
  if($delta != 0 && !empty($edit)) {
    $query = db_merge('exchange_links_blocks')
      ->key(array('bid' => $delta))
      ->fields(array(
        'service' => $edit['exchange_links_service'],
        'user' => $edit['exchange_links_user'],
        'debug' => $edit['exchange_links_debug'],
        'show_code' => $edit['exchange_links_show_code'],
      ))
      ->execute();
  }
}

/**
 * Implements hook_block_view().
 */
function exchange_links_block_view($delta = 0) {
  $data = array();
  if($delta != 0) {
    $block = exchange_links_block_get($delta);
    $data['subject'] = NULL;
    $data['content'] = "Service $block->service </br>
      User $block->user </br>
      Debug $block->debug </br>
      Show code $block->show_code </br>";
  }
  return $data;
}

/**
 * Implements hook_block_info().
 */
function exchange_links_block_info() {
  $blocks = array();
  $result = db_select('exchange_links_blocks', 'blocks')
    ->fields('blocks')
    ->execute();
  while($record = $result->fetchObject()) {
    $info = "$record->service: $record->user";
    if (drupal_strlen($info) > 30) {
       $blocks[$record->bid]['info'] = drupal_substr($info, 0, 25) . '...';
    }
    else {
      $blocks[$record->bid]['info'] = $info;
    }
    $blocks[$record->bid]['cache'] = DRUPAL_NO_CACHE;
  }
  return $blocks;
}

/**
 * Implements hook_form_FORM_ID_alter()
 * place form admin/structure/block
 */
function exchange_links_form_block_admin_display_form_alter(&$form, $form_state) {
  foreach($form['blocks'] as $key => $block) {
    if($block['module']['#value'] == 'exchange_links') {
      $form['blocks'][$key]['delete'] = array(
        '#type' => 'link',
        '#title' => t('delete'),
        '#href' => 'admin/structure/block/manage/exchange_links/' . $block['delta']['#value'] . '/delete',
      );
    }
  }
}

/**
 * Returns information from database about a created block.
 * @param bid
 *   ID of the block to get information for.
 * @return object of information stored in the database for this block.
 * see exchange_links_schema()
 */
function exchange_links_block_get($bid) {
  return db_select('exchange_links_blocks', 'blocks')
    ->fields('blocks')
    ->condition('bid', $bid, '=')
    ->execute()
    ->fetchObject();
}

/**
 * The list of supported services
 * @return accociative array of services
 *   array('machin_name_of_services' => 'human_name_of_services')
 */
function exchange_links_services() {
  $support_services = array(
    EXCHANGE_LINKS_SAPE => 'Sape',
    EXCHANGE_LINKS_MAINLINK => 'MainLink',
    EXCHANGE_LINKS_LINKFEED => 'LinkFeed',
    EXCHANGE_LINKS_SETLINK => 'SetLinks',
  );
  return $support_services;
}
