<?php

/**
 * Implements hook_block_info()
 */
function mainlink_block_block_info() {
  $blocks['mainlink_block_links'] = array (
    'info' => t('Mainlink links block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['mainlink_block_articles'] = array (
    'info' => t('Mainlink articles block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure()
 */
function mainlink_block_block_configure($delta = '') {
  $form = array();
  $default_values = array();
  if ($delta == 'mainlink_block_links' || $delta == 'mainlink_block_articles') {
    $form['mainlink_block_user'] = array(
      '#type' => 'textfield',
      '#required' => TRUE,
      '#title' => t('User name'),
      '#description' => t('Mainlink user name'),
      '#default_value' => variable_get('mainlink_block_user'),
    );
    $form['mainlink_block_options'] = array(
      '#type' => 'container',
      '#tree' => TRUE,
    );
    $form['mainlink_block_options']['test'] = array(
      '#type' => 'checkbox',
      '#title' => t('Test'),
      '#description' => t('Show test elements'),
    );
    $form['mainlink_block_options']['test_num'] = array(
      '#type' => 'textfield',
      '#title' => t('Number of test elements'),
      '#description' => t('How many test elements to show'),
    );
    if($delta == 'mainlink_block_links') {
      $default_values = variable_get('mainlink_block_links_options');
    }
    if($delta == 'mainlink_block_articles') {
      $default_values = variable_get('mainlink_block_articles_options');
    }
    if(!empty($default_values)) {
      foreach($form['mainlink_block_options'] as $option => $value) {
        if(is_array($value)) {
          $form['mainlink_block_options'][$option]['#default_value'] = $default_values[$option];
        }
      }
    }
  }
  return $form;
}

/**
 * Implements hook_block_save()
 */
function mainlink_block_block_save($delta = '', $edit = array()) {
  if($delta == 'mainlink_block_links' || $delta == 'mainlink_block_articles') {
    variable_set('mainlink_block_user', $edit['mainlink_block_user']);
  }
  if($delta == 'mainlink_block_links') {
    variable_set('mainlink_block_links_options', $edit['mainlink_block_options']);
  }
  if($delta == 'mainlink_block_articles') {
    variable_set('mainlink_block_articles_options', $edit['mainlink_block_options']);
  }
}

/**
 * Implements hook_block_view()
 */
function mainlink_block_block_view($delta = '') {
  $block = array();
  if ($delta == 'mainlink_block_links' || $delta == 'mainlink_block_articles') {
    $block['subject'] = NULL;
    $user = variable_get('mainlink_block_user');
    if(!empty($user)) {
      $options = array();
      $options['USERNAME'] = $user;
      $mainlink_dir = DRUPAL_ROOT . '/' . $options['USERNAME'];
      $mainlink_php = "$mainlink_dir/mainlink.php";
      if(file_prepare_directory("$mainlink_dir") && file_prepare_directory("$mainlink_dir/data")) {
        if(file_exists($mainlink_php)) {
          require_once($mainlink_php);
          $options['charset'] = 'utf';
          if ($delta == 'mainlink_block_links') {
            $options['CODE_TYPE'] = 'l';
            $options += variable_get('mainlink_block_links_options');
          }
          if ($delta == 'mainlink_block_articles') {
            $options['CODE_TYPE'] = 'a';
            $options += variable_get('mainlink_block_articles_options');
          }
          $mainlink_client = new MLClient($options);
          $block['content'] = $mainlink_client->build_links();
        }
        else {
          drupal_set_message(t("File '$mainlink_php' not exist"), 'error');
        }
      }
      else {
        drupal_set_message(t("Directory '$mainlink_dir', '$mainlink_dir/data' not exist or not writable"), 'error');
      }
    }
  }
  return $block;
}
