<?php

/**
 * Implements hook_block_info()
 */
function trustlink_block_block_info() {
  $blocks['trustlink_block_links'] = array (
    'info' => t('Trustlink links block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure()
 */
function trustlink_block_block_configure($delta = '') {
  $form = array();
  $default_values = array();
  if ($delta == 'trustlink_block_links') {
    $form['trustlink_block_user'] = array(
      '#type' => 'textfield',
      '#required' => TRUE,
      '#title' => t('User name'),
      '#description' => t('Trustlink user name'),
      '#default_value' => variable_get('trustlink_block_user'),
    );
    $form['trustlink_block_options'] = array(
      '#type' => 'container',
      '#tree' => TRUE,
    );
    $form['trustlink_block_options']['verbose'] = array(
      '#type' => 'checkbox',
      '#title' => t('Verbose'),
      '#description' => t('Show errors'),
    );
    $form['trustlink_block_options']['force_show_code'] = array(
      '#type' => 'checkbox',
      '#title' => t('Force show code'),
      '#description' => t('Always show check code'),
    );
    $default_values = variable_get('trustlink_block_links_options');
    if(!empty($default_values)) {
      foreach($form['trustlink_block_options'] as $option => $value) {
        if(is_array($value)) {
          $form['trustlink_block_options'][$option]['#default_value'] = $default_values[$option];
        }
      }
    }
  }
  return $form;
}

/**
 * Implements hook_block_save()
 */
function trustlink_block_block_save($delta = '', $edit = array()) {
  if($delta == 'trustlink_block_links') {
    variable_set('trustlink_block_user', $edit['trustlink_block_user']);
    variable_set('trustlink_block_links_options', $edit['trustlink_block_options']);
  }
}

/**
 * Implements hook_block_view()
 */
function trustlink_block_block_view($delta = '') {
  $block = array();
  if ($delta == 'trustlink_block_links') {
    $block['subject'] = NULL;
    $user = variable_get('trustlink_block_user');
    if(!empty($user)) {
      if (!defined('TRUSTLINK_USER')) {
        define('TRUSTLINK_USER', $user);
      }
      $trustlink_dir = DRUPAL_ROOT . '/' . TRUSTLINK_USER;
      $trustlink_php = "$trustlink_dir/trustlink.php";
      if(file_prepare_directory($trustlink_dir)) {
        if(file_exists($trustlink_php)) {
          require_once($trustlink_php);
          $options = array();
          $options['charset'] = 'utf-8';
          $options += variable_get('trustlink_block_links_options');
          $trustlink_links = new TrustlinkClient($options);
          $block['content'] = $trustlink_links->build_links();
        }
        else {
          drupal_set_message(t("File '$trustlink_php' not exist"), 'error');
        }
      }
      else {
        drupal_set_message(t("Directory '$trustlink_dir' not exist or not writable"), 'error');
      }
    }
  }
  return $block;
}
